export const Users = [
    {
      id:1,
      profilePicture: "assets/person/img02.jpg",
      username: "kamau johnson",
    },
    {
      id:2,
      profilePicture: "assets/person/img03.jpg",
      username: "Eluid martha ",
    },
    {
      id:3,
      profilePicture: "assets/person/img04.jpg",
      username: "Alex waweru",
    },
    {
      id:4,
      profilePicture: "assets/person/img05.jpg",
      username: "Dora Wakio",
    },
    {
      id:5,
      profilePicture: "assets/person/img05.jpg",
      username: "Gordon adera",
    },
    {
      id:6,
      profilePicture: "assets/person/img1.jpg",
      username: "Murcus Rashford",
    },
    {
      id:7,
      profilePicture: "assets/person/img02.jpg",
      username: "Bruno okinyi",
    },
    {
      id:8,
      profilePicture: "assets/person/img02.jpg",
      username: "Ron drury",
    },
    {
      id:9,
      profilePicture: "assets/person/img03.jpg",
      username: "Andre Onana",
    },
    {
      id:10,
      profilePicture: "assets/person/img04.jpg",
      username: "Haron kamau ",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "assets/post/img04.png",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "assets/post/img07.png",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "assets/post/img01.png",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "assets/post/img02.png",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "assets/post/img03.png",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "assets/post/img04.png",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "assets/post/img05.png",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "assets/post/img06.png",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "assets/post/img07.png",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "assets/post/img08.png",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];